spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/timeTrackerdb?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true